# Generated by Django 5.0.6 on 2024-06-25 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
